### PR TITLE
P13_reg Z(r) expansion correction

### PR DESCRIPTION
**Pull request by xfangcosmo**
Fix a typo and correct high-order expansion coeff in P13_reg

### CODE REVIEW

**Comment by CarterDW** [comment]
hey @xfangcosmo , we have been trying to replicate the fix for the expansion coefficients in P13_reg but we are only replicating our own results. Do you have a notebook or something where you do the calculation out to get these values that you could send so we can compare? Thank you so much!

**Comment by xfangcosmo** [comment]
@CarterDW I couldn't find the notebook as it was done a few years ago. The idea was to include more high-order terms in the series expansion of Z(r) at low and high r. Essentially the terms were from the log function. Do you see the same results when more terms are included?

**Comment by CarterDW** [comment]
@xfangcosmo when you say higher order do you mean adding terms to the Taylor expansion of the log function? We did not add any new terms to our Taylor expansion, but I only see a fix to the constants in front of two terms, whereas adding onto the Taylor series should add more terms at higher and lower r dependency I would expect?

**Comment by CarterDW** [comment]
Actually one of our colleagues did add terms and we see these new constants out front as well! Thank you for this

**Comment by xfangcosmo** [comment]
@CarterDW Great, thanks for checking! Someone may want to check the expansions of other P13-type terms as well, although I don't think it can bring any substantial difference.

**Review by dderienzo — APPROVED** [review]
Fixes issue #10.

Checked and reproduced in Mathematica Notebook. Terms added at higher expansion are insignificant in power spectrum, however typo of 0.5 to 5.0 is significant.

**Pull request merged**
